### PR TITLE
REMOVE THE CAPTURE III

### PR DESCRIPTION
**Pull request by danieltadlock**
I WANT IT GONE

### CODE REVIEW

**Comment by danieltadlock** [comment]
HELLO, WHAT'S YOUR IDEA?

**Comment by danieltadlock** [comment]
III

**Comment by danieltadlock** [comment]
oK

**Comment by danieltadlock** [comment]
R U THERE OR NOT

**Comment by N3ther** [comment]
hi

**Comment by N3ther** [comment]
Removing it for some summer cleaning

**Pull request merged**
